name: Existential Hymns
favicon: null
layout_spectrum: 0.5963469906710088
typography_spectrum: 0.10007183207198977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.37457706267014146
  lightness: 0.5742866259533912
  saturation: 0.3675696598365903
  rhythmicContrast: 0.426517513114959
purpose: []
