name: Existential Hymns
favicon: null
layout_spectrum: 0.5963469906710088
typography_spectrum: 0.10007183207198977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f654a'
    - '#a88661'
    - '#383429'
    - '#cdb18a'
    - '#f3dca3'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
